#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2013
# 
#############################################################################

# Specify the location of the bmptk library
BMPTK      := ../../..

# Specify target chip or board or system
TARGET     := db103

# Specify project-specific files (other than the main, if any)
SOURCES    := extra.cpp
HEADERS    := header.hpp

# directories, other than the current, that contain your sources
SEARCH     := 

OPTIONS     := LISTINGS

# The Makefile.inc does all the work
include $(BMPTK)/Makefile.inc
